[tool.poetry]
name = "innohassle-room-booking"
version = "0.1.0"
description = ""
authors = ["one-zero-eight <https://t.me/one_zero_eight>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.0"
pydantic = "^2.9.2"
cryptography = "^43.0.1"
authlib = "^1.3.2"
colorlog = "^6.8.2"
fastapi-swagger = "^0.2.3"
icalendar = "^5.0.13"
uvicorn = "^0.30.6"

[tool.poetry.group.prod.dependencies]
gunicorn = "^23.0.0"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
ruff = "^0.6.7"
pre-commit = "^3.7.1"

[tool.poetry.group.ci]
optional = true
[tool.poetry.group.ci.dependencies]
pydantic = "^2.8.2"
pre-commit = "^3.7.1"

[tool.ruff]
line-length = 120
lint.ignore = [
    # wildcard imports are fine
    "F403",
    "F405",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
